# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=140, null=True, verbose_name='Stripe ID')),
                ('stripe_email', models.EmailField(max_length=254, verbose_name='email')),
                ('first_name', models.CharField(max_length=140, verbose_name='first name')),
                ('last_name', models.CharField(max_length=140, verbose_name='last name')),
                ('phone', models.CharField(max_length=140, verbose_name='phone')),
                ('address1', models.CharField(max_length=140, verbose_name='address 1')),
                ('address2', models.CharField(blank=True, max_length=140, null=True, verbose_name='address 2')),
                ('city', models.CharField(max_length=140, verbose_name='city')),
                ('state', models.CharField(max_length=140, verbose_name='state')),
                ('zip_code', models.CharField(max_length=10, verbose_name='zip code')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'stripe customers',
                'verbose_name': 'stripe customer',
                'get_latest_by': 'created',
            },
        ),
    ]
