# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_auto_20160616_1144'),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('donate_message', models.TextField(blank=True, default='', help_text='Top orange box Donate text. Use CSS class .message-text                    for the messange, and .message-attribution for the                    quote attribution.', verbose_name='Donation top box message')),
                ('donate_section_top', models.TextField(blank=True, default='', help_text='Content box for the Donate section above the blue links.', verbose_name='Donate section top')),
                ('donate_section_bottom', models.TextField(blank=True, default='', help_text='Content box for the Donate section below the blue links.', verbose_name='Donate section bottom')),
                ('donation_values', models.CharField(blank=True, default='25,100,250,Other', help_text='Enter donation values separated by commas. DO NOT INCLUDE "$".                    Commas will be added to values over $1,000 automatically.', max_length=80, verbose_name='Donation values')),
                ('tell_section', models.TextField(blank=True, default='', help_text='Text for the Tell your friends section of                     the Donate page.', verbose_name='Tell your friends')),
                ('donate_message_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_top_box_image', to='media_manager.MediaItem', verbose_name='Donation top box image')),
            ],
            options={
                'get_latest_by': 'created',
                'verbose_name_plural': 'Donate Page',
                'verbose_name': 'Donate Page',
            },
        ),
    ]
