# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='donation_values',
        ),
    ]
