# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 18:44
from __future__ import unicode_literals

from django.db import migrations
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_donate_donation_values'),
    ]

    def initialize_dates(apps, schema_editor):
        model_names = ["donate", ]
        for model_name in model_names:
            model = apps.get_model("donation", model_name)
            for obj in model.objects.all():
                if not obj.created:
                    obj.created = now()
                if not obj.updated:
                    obj.updated = now()
                obj.save()

    def reverse(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(initialize_dates, reverse)
    ]
