# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_auto_20160728_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='donate_message_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_top_box_image', to='media_manager.MediaItem', verbose_name='Donation top box image'),
        ),
    ]
