# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20160608_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='posts/', verbose_name='Featured Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='works_display_five',
            field=models.CharField(blank=True, default='', help_text='25 characters max', max_length=25, verbose_name='Works 5 Label'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='works_display_four',
            field=models.CharField(blank=True, default='', help_text='25 characters max', max_length=25, verbose_name='Works 4 Label'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='works_display_one',
            field=models.CharField(blank=True, default='', help_text='25 characters max', max_length=25, verbose_name='Works 1 Label'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='works_display_three',
            field=models.CharField(blank=True, default='', help_text='25 characters max', max_length=25, verbose_name='Works 3 Label'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='works_display_two',
            field=models.CharField(blank=True, default='', help_text='25 characters max', max_length=25, verbose_name='Works 2 Label'),
        ),
    ]
