# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20160608_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedHeadlineArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_headline_articles_as_homepage', to='pages.Article')),
            ],
            options={
                'verbose_name_plural': 'Related Headline Articles',
                'verbose_name': 'Related Headline Article',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_featured_2', to='pages.Article', verbose_name='Second Feature'),
        ),
        migrations.AddField(
            model_name='relatedheadlinearticle',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_headline_articles_as_homepage', to='pages.HomePage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='headlines',
            field=models.ManyToManyField(blank=True, null=True, related_name='home_more_headlines', through='pages.RelatedHeadlineArticle', to='pages.Article', verbose_name='More Headlines'),
        ),
    ]
