# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:28
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.timezone import utc, now


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20160610_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ('-go_live_on_date',), 'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='status',
        ),
        migrations.AddField(
            model_name='homepage',
            name='can_go_live',
            field=models.BooleanField(default=False),
        ),
    ]
