# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20160614_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='go_live_on_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 14, 14, 33, 16, 927627, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
