# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_homepage_go_live_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='go_live_on_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
