# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20160614_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='go_live_on_date',
            field=models.DateTimeField(help_text='Times are in US/Pacific', unique=True),
        ),
    ]
