# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20160615_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='facebook_share_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='atom',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured_image',
        ),
        migrations.AlterField(
            model_name='article',
            name='facebook_image',
            field=models.ForeignKey(blank=True, help_text='Image size should be 600 x 315 for best results (or 1200 x 630 for high resolution)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_with_facebook_image', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aproject_with_image', to='media_manager.MediaItem', verbose_name='Featured Image'),
        ),
    ]
