# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20160620_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('order',), 'permissions': (('can_change_article_status', 'Can change status of articles'),), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order', '-publish_date'), 'permissions': (('can_change_project_status', 'Can change status of projects'),), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
