# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20160620_1700'),
        ('pages', '0022_auto_20160621_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(help_text='Used for internal tracking only.', max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='CALmatters tagline')),
                ('mission', models.TextField(blank=True, default='', help_text='Content for the Mission section of the About page.', verbose_name='Mission')),
                ('team', models.TextField(blank=True, default='', help_text='Left content for the Team section of the About page.', verbose_name='Team')),
                ('partners', models.TextField(blank=True, default='', help_text='Left content for the Partners section of the About page.', verbose_name='Partners')),
                ('funders', models.TextField(blank=True, default='', help_text='Left content for the Funders/Supporters section of the About page.', verbose_name='Funders/Supporters')),
                ('funders_list', models.TextField(blank=True, default='', help_text='List of names for the right hand section of Funders/Supporters.', verbose_name='Funders Names')),
                ('donate_message', models.CharField(blank=True, max_length=300)),
                ('jobs_message', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'About Pages',
                'verbose_name': 'About Page',
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='AboutPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.About')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Partner')),
            ],
            options={
                'verbose_name_plural': 'Partner Logos',
                'ordering': ('order',),
                'verbose_name': 'Partner Logo',
            },
        ),
        migrations.AlterField(
            model_name='relatedatom',
            name='atom_layout',
            field=models.CharField(choices=[('image', 'Image Layout'), ('embedded', 'Embedded HTML')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='about',
            name='partner_logos',
            field=models.ManyToManyField(blank=True, through='pages.AboutPartner', to='business.Partner', verbose_name='Partner Logos'),
        ),
    ]
