# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20160621_1714'),
        ('pages', '0024_auto_20160621_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.About')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Person')),
            ],
            options={
                'verbose_name_plural': 'Staff People',
                'ordering': ('order',),
                'verbose_name': 'Staff Person',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='staff',
            field=models.ManyToManyField(blank=True, through='pages.AboutStaff', to='business.Person'),
        ),
    ]
