# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20160621_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutstaff',
            name='about',
        ),
        migrations.RemoveField(
            model_name='aboutstaff',
            name='person',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staff',
        ),
        migrations.DeleteModel(
            name='AboutStaff',
        ),
    ]
