# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 01:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import fkchooser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20160622_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_2',
            field=fkchooser.fields.PopupForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_featured_2', to='pages.Article', verbose_name='Second Feature'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='primary_article',
            field=fkchooser.fields.PopupForeignKey(help_text='Article displayed front and center, largest', on_delete=django.db.models.deletion.CASCADE, related_name='primary_on_homepages', to='pages.Article', verbose_name='Primary Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='secondary_article_left',
            field=fkchooser.fields.PopupForeignKey(help_text='Article displayed below primary article to the left', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_left_on_homepages', to='pages.Article', verbose_name='Left Secondary Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='secondary_article_right',
            field=fkchooser.fields.PopupForeignKey(help_text='Article displayed below primary article to the right', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_right_on_homepages', to='pages.Article', verbose_name='Right Secondary Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='the_basics_four',
            field=fkchooser.fields.PopupForeignKey(help_text='Four Article in the The Basics', on_delete=django.db.models.deletion.CASCADE, related_name='basics_four_on_homepages', to='pages.Article', verbose_name='Bottom Article in The Basics'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='the_basics_one',
            field=fkchooser.fields.PopupForeignKey(help_text='First Article in the The Basics', on_delete=django.db.models.deletion.CASCADE, related_name='basics_one_on_homepages', to='pages.Article', verbose_name='Top Article in The Basics'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='the_basics_three',
            field=fkchooser.fields.PopupForeignKey(help_text='Third Article in the The Basics', on_delete=django.db.models.deletion.CASCADE, related_name='basics_three_on_homepages', to='pages.Article', verbose_name='Third Article in The Basics'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='the_basics_two',
            field=fkchooser.fields.PopupForeignKey(help_text='Second Article in the The Basics', on_delete=django.db.models.deletion.CASCADE, related_name='basics_two_on_homepages', to='pages.Article', verbose_name='Second Article in The Basics'),
        ),
        migrations.AlterField(
            model_name='relatedatom',
            name='atom',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_atom_atoms', to='pages.Atom'),
        ),
        migrations.AlterField(
            model_name='relatedheadlinearticle',
            name='article',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_headline_articles_as_homepage', to='pages.Article'),
        ),
    ]
