# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20160627_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='custom_post_type',
            field=models.CharField(choices=[('articles', 'Articles'), ('expertperspectives', 'Expert Perspectives'), ('external', 'External Link'), ('press', 'Press Release'), ('readerreactions', 'Reader Reactions'), ('updates', 'Updates'), ('basics', 'The Basics')], default='articles', max_length=30, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='atom',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
