# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import fkchooser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20160629_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsortableexpertperspectivesarticle',
            name='article',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Article'),
        ),
        migrations.AlterField(
            model_name='projectsortablefeaturedarticle',
            name='article',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Article'),
        ),
        migrations.AlterField(
            model_name='projectsortablereaderreactionsarticle',
            name='article',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Article'),
        ),
        migrations.AlterField(
            model_name='projectsortablerelatedarticle',
            name='article',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Article'),
        ),
        migrations.AlterField(
            model_name='projectsortableupdatesarticles',
            name='article',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Article'),
        ),
        migrations.AlterField(
            model_name='projectsortablevisualizations',
            name='atom',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Atom'),
        ),
        migrations.AlterField(
            model_name='relatedarticle',
            name='article',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_post', to='pages.Article'),
        ),
        migrations.AlterField(
            model_name='relatedarticle',
            name='related_article',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='pages.Article'),
        ),
    ]
