# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='politics_quote_attribution',
            field=models.CharField(blank=True, default='', max_length=135),
        ),
    ]
