# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20160728_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='go_live_on_date',
            field=models.DateTimeField(blank=True, help_text='Times are in US/Pacific', null=True, unique=True),
        ),
    ]
