# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20160728_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='template_filename',
            field=models.CharField(default='home.html', help_text="Can provide an alternative home page template to use.  If you aren't sure what to do, then do not change this value.", max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Choices limited to users who are staff (is_staff=True).', related_name='authors_articles', to='business.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, help_text='Auto-generated from the title when blank.  slug is used in the url that relates to this content', max_length=2000, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='atom',
            name='slug',
            field=models.CharField(blank=True, help_text='Auto-generated from the title when blank.  slug is used in the url that relates to this content', max_length=2000, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slug',
            field=models.CharField(blank=True, help_text='Auto-generated from the title when blank.  slug is used in the url that relates to this content', max_length=2000, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='onramp',
            name='slug',
            field=models.CharField(blank=True, help_text='Auto-generated from the title when blank.  slug is used in the url that relates to this content', max_length=2000, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, help_text='Auto-generated from the title when blank.  slug is used in the url that relates to this content', max_length=2000, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=models.CharField(blank=True, help_text='Auto-generated from the title when blank.  slug is used in the url that relates to this content', max_length=2000, null=True, verbose_name='Slug'),
        ),
    ]
