# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_auto_20160616_1144'),
        ('pages', '0036_auto_20160815_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='politics_alternate_image',
            field=models.ForeignKey(blank=True, help_text="Show this image instead of the author's image.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_with_politics_image', to='media_manager.MediaItem', verbose_name='Politics Image'),
        ),
    ]
