# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_homepage_politics_alternate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='politics_alternate_image',
            new_name='image',
        ),
    ]
