# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fkchooser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_auto_20160822_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalHomePageArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addition_hp_articles_as_homepage', to='pages.Article')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addition_hp_articles_as_homepage', to='pages.HomePage')),
            ],
            options={
                'verbose_name': 'Addition Article',
                'verbose_name_plural': 'Addiiton Articles',
                'ordering': ('order',),
            },
        ),
    ]
