# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_additionalhomepagearticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalhomepagearticle',
            options={'ordering': ('order',), 'verbose_name': 'Additional Article', 'verbose_name_plural': 'Addiitonal Articles'},
        ),
    ]
