# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 18:40
from __future__ import unicode_literals

import categories.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_auto_20160616_1144'),
        ('categories', '0010_auto_20160815_1532'),
        ('pages', '0039_additionalhomepagearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', max_length=135, verbose_name='Description (135 Chars)')),
                ('slug', models.CharField(blank=True, help_text='Auto-generated from the title when blank.  slug is used in the url that relates to this content', max_length=2000, null=True, verbose_name='Slug')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities_with_image', to='media_manager.MediaItem', verbose_name='Icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', max_length=135, verbose_name='Description (135 Chars)')),
                ('slug', models.CharField(blank=True, help_text='Auto-generated from the title when blank.  slug is used in the url that relates to this content', max_length=2000, null=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('more_information', models.TextField(blank=True, null=True, verbose_name='More information')),
                ('order', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='props_in_category', to='categories.Category', verbose_name='Categories')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props_with_image', to='media_manager.MediaItem', verbose_name='Title background image')),
                ('opponents', models.ManyToManyField(related_name='props_with_opponents', to='pages.PoliticalEntity')),
                ('supporters', models.ManyToManyField(related_name='props_with_supporter', to='pages.PoliticalEntity')),
            ],
            options={
                'verbose_name_plural': 'Propositions',
                'verbose_name': 'Proposition',
                'ordering': ('order',),
            },
            bases=(models.Model, categories.mixins.CategoryMixin),
        ),
        migrations.CreateModel(
            name='VoterGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', max_length=135, verbose_name='Description (135 Chars)')),
                ('slug', models.CharField(blank=True, help_text='Auto-generated from the title when blank.  slug is used in the url that relates to this content', max_length=2000, null=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('can_go_live', models.BooleanField(default=False)),
                ('go_live_on_date', models.DateTimeField(blank=True, help_text='Times are in US/Pacific', null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='additionalhomepagearticle',
            options={'ordering': ('order',), 'verbose_name': 'Additional Article', 'verbose_name_plural': 'Addiitonal Articles'},
        ),
        migrations.AddField(
            model_name='proposition',
            name='voter_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_propositions', to='pages.VoterGuide'),
        ),
    ]
