# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_auto_20160912_1303'),
        ('pages', '0040_auto_20160912_1140'),
    ]

    operations = [
    ]
