# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_auto_20160913_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterguide',
            name='category_in_menu',
            field=models.BooleanField(default=True, help_text='If checked, the main menu will show categories.  If not checked the main menu will show propositions.', verbose_name='Category in menus'),
        ),
    ]
