# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fkchooser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_auto_20160914_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropRelatedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('proposition', fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_related', to='pages.Proposition')),
                ('related_article', fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='pages.Article')),
            ],
            options={
                'verbose_name': 'Related Article',
                'verbose_name_plural': 'Related Articles',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='proposition',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='contained_in_related', through='pages.PropRelatedArticle', to='pages.Proposition', verbose_name='Related Articles'),
        ),
    ]
