# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_auto_20160915_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='opponents',
            field=models.ManyToManyField(blank=True, related_name='props_with_opponents', to='pages.PoliticalEntity'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='props_with_supporter', to='pages.PoliticalEntity'),
        ),
    ]
