# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_voterguide_alternate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterguide',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
