# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_voterguide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='opponents_title',
            field=models.CharField(blank=True, default='Opponents', max_length=50, verbose_name='Opponents Title'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='supporters_title',
            field=models.CharField(blank=True, default='Supporters', max_length=50, verbose_name='Supporters Title'),
        ),
    ]
