# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_auto_20160919_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='infogram_content_content',
            field=models.TextField(blank=True, default='', verbose_name='Infogram title content'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='infogram_content_title',
            field=models.CharField(blank=True, default="Here's How I See It", max_length=50, verbose_name='Infogram title'),
        ),
    ]
