# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_auto_20160919_1401'),
        ('pages', '0052_auto_20160919_1301'),
    ]

    operations = [
    ]
