# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_auto_20160616_1144'),
        ('pages', '0056_auto_20160919_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterguide',
            name='dark_icon_image',
        ),
        migrations.AddField(
            model_name='proposition',
            name='dark_icon_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props_with_dark_icon_image', to='media_manager.MediaItem', verbose_name='Dark icon image'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='icon_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props_icon_image', to='media_manager.MediaItem', verbose_name='Icon Image'),
        ),
    ]
