# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_auto_20160919_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='icon_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props_icon_image', to='media_manager.MediaItem', verbose_name='Light Icon Image'),
        ),
        migrations.AlterField(
            model_name='voterguide',
            name='icon_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voterguides_icon_image', to='media_manager.MediaItem', verbose_name='Icon image'),
        ),
    ]
