# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_auto_20160919_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='headline_image_height',
            field=models.CharField(choices=[('tall', 'Tall'), ('short', 'Short')], default='tall', max_length=30, verbose_name='Headline Image Height'),
        ),
    ]
