# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_proposition_headline_image_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='headline_image_offset',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Headline Image Offset %'),
        ),
    ]
