# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0066_auto_20160923_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='facebook_image',
            field=models.ForeignKey(blank=True, help_text='Image size should be 600 x 315 for best results (or 1200 x 630 for high resolution)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_with_facebook_image', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_with_image', to='media_manager.MediaItem', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='atom',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atom_with_image', to='media_manager.MediaItem', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text="Show this image instead of the author's image.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_with_politics_image', to='media_manager.MediaItem', verbose_name='Politics Image'),
        ),
        migrations.AlterField(
            model_name='politicalentity',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities_with_image', to='media_manager.MediaItem', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aproject_with_image', to='media_manager.MediaItem', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='dark_icon_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='props_with_dark_icon_image', to='media_manager.MediaItem', verbose_name='Dark icon image'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='facebook_image',
            field=models.ForeignKey(blank=True, help_text='Image size should be 600 x 315 for best results (or 1200 x 630 for high resolution)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposition_with_facebook_image', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='icon_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='props_icon_image', to='media_manager.MediaItem', verbose_name='Light Icon Image'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='props_with_image', to='media_manager.MediaItem', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='voterguide',
            name='dark_icon_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voterguides_dark_icon_image', to='media_manager.MediaItem', verbose_name='Dark Icon image'),
        ),
        migrations.AlterField(
            model_name='voterguide',
            name='facebook_image',
            field=models.ForeignKey(blank=True, help_text='Image size should be 600 x 315 for best results (or 1200 x 630 for high resolution)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voterguides_with_facebook_image', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='voterguide',
            name='icon_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voterguides_icon_image', to='media_manager.MediaItem', verbose_name='Icon image'),
        ),
        migrations.AlterField(
            model_name='voterguide',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voterguides_with_image', to='media_manager.MediaItem', verbose_name='Headline image'),
        ),
    ]
