# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
