# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20160527_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', max_length=135, verbose_name='Description (135 Chars)'),
        ),
    ]
