# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20160628_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, help_text='Will be auto-generated from the title.', max_length=2000, null=True, verbose_name='Slug'),
        ),
    ]
