# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 18:41
from __future__ import unicode_literals

from django.db import migrations
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_category_preferred'),
    ]

    def initialize_dates(apps, schema_editor):
        model_names = ["category",]
        for model_name in model_names:
            model = apps.get_model("categories", model_name)
            for obj in model.objects.all():
                if not obj.created:
                    obj.created = now()
                if not obj.updated:
                    obj.updated = now()
                obj.save()

    def reverse(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(initialize_dates, reverse)
    ]
