# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20160728_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, help_text='Auto-generated from the title when blank.  slug is used in the url that relates to this content', max_length=2000, null=True, verbose_name='Slug'),
        ),
    ]
