# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'verbose_name': 'Job Listing', 'verbose_name_plural': 'Job Listings'},
        ),
        migrations.AlterModelOptions(
            name='jobpage',
            options={'verbose_name': 'Job Page', 'verbose_name_plural': 'Job Pages'},
        ),
    ]
