"""
Django settings for calmat_ng project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

PROJECT_NAME = "CALmatters"

MASTHEAD_DEFAULT = ("A nonprofit, nonpartisan media venture producing "
                    "compelling stories on policies, personalities and "
                    "money in Sacramento.")

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h5ku96j&m-qgpjcdxy^#xwm13-p7=f#itm(qnkx2^=pk99!0p4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'admin_tools',
    # 'admin_tools.theming',
    # 'admin_tools.menu',
    'admin_tools.dashboard',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'versatileimagefield',
    'adminsortable2',
    'fkchooser',
    'categories',
    'calmat_ng',
    'sites',
    'pages',
    'business',
    'donation',
    'employment',
    'media_manager',
    'debug_toolbar',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'calmat_ng.urls'

# GLOBAL_TEMPLATES = os.path.join(BASE_DIR, 'templates/')


ADMIN_TEMPLATES = os.path.join(BASE_DIR, 'admin_templates/')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ADMIN_TEMPLATES, ],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'calmat_ng.context_processors.categories',
                'calmat_ng.context_processors.projects',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'admin_tools.template_loaders.Loader']
        },
    },
]

WSGI_APPLICATION = 'calmat_ng.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'calmat_ng',
        'USER': 'calmatters',
        'PASSWORD': 'calmatters_db1',
        'HOST': 'localhost',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATICFILES_FINDERS = (
    #  Since all static is either in calmat_ng, or other apps
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
 )


#STATICFILES_DIRS = [
#    # Directory in the git tree
#    os.path.join(BASE_DIR, "calmat_ng", "static"),
#]

# Directory above git root
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static")

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media")

MEDIA_URL = '/media/'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG'),
        },
    },
}

ARTICLES_PER_PAGE = 20
IMAGES_UPLOADED_MAX_WIDTH_PX = 1200

ADMIN_TOOLS_INDEX_DASHBOARD = 'dashboard.CustomIndexDashboard'

# Stripe API Keys
STRIPE_SECRET_KEY = 'sk_test_zaQg1oB9QzLvU4M1jcV4wkO1' # MS test account
STRIPE_PUBLIC_KEY = 'pk_test_OQ60th2VFcDtRwCHU5H0MdbU' # MS test account

SEND_SUBSCRIPTIONS_TO_MAIL_CHIMP = False
MAILCHIMP_API_KEY = ''
MAILCHIMP_MAIN_LIST_ID = ''
MAILCHIMP_GROUPING_ID = 11649  # u'Subject Interest'

try:
    from .local_settings import *
except ImportError:
    print("Must configure a local_settings.py module, even if it's empty.")
    raise
