# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 00:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Article'),
        ),
        migrations.AddField(
            model_name='partnerarticle',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Partner'),
        ),
        migrations.AddField(
            model_name='partner',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='partners', to='categories.Category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='partner',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners_by_owner', to='business.PartnerOwner'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(help_text=b'Connects the `author` object to a `User`to pull in the profile photo on a post.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='partnerarticle',
            unique_together=set([('article', 'partner', 'date_published', 'notes')]),
        ),
    ]
