# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20160527_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='partnerowner',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
