# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20160527_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='content',
        ),
    ]
