# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_author_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, default='', max_length=135, verbose_name='Description (135 Chars)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='facebook_url',
            field=models.CharField(blank=True, default='', help_text='Adding a Facebook url will enable Facebook authoring.  i.e. https://www.facebook.com/your_name', max_length=256, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='author',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='authors/', verbose_name='Author Image'),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text='Adding a Facebook url will enable Facebook authoring.  i.e. https://www.facebook.com/your_name', max_length=256, verbose_name='Twitter @'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(help_text='Connects the `author` object to a `User`to pull in the profile photo on a post.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, default='', max_length=135, verbose_name='Description (135 Chars)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='featured_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='partners/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='featured_image_large',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='partners/', verbose_name='Featured Image - Large'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='link_to_articles',
            field=models.BooleanField(default=True, help_text='Add link to article list'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('distribution', 'Distribution'), ('data', 'Data')], default='distribution', max_length=80),
        ),
        migrations.AlterField(
            model_name='partnerarticle',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/published'),
        ),
        migrations.AlterField(
            model_name='partnerarticle',
            name='fulltext_or_mention',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('Full Text Publish', 'Full Text Publish'), ('Mention/Aggregation', 'Mention/Aggregation')], default=('Not Specified', 'Not Specified'), max_length=19, verbose_name='Publish Type'),
        ),
        migrations.AlterField(
            model_name='partnerarticle',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partnerarticle',
            name='properly_credited',
            field=models.NullBooleanField(verbose_name='Properly credited?'),
        ),
        migrations.AlterField(
            model_name='partnerarticle',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerowner',
            name='description',
            field=models.TextField(blank=True, default='', max_length=135, verbose_name='Description (135 Chars)'),
        ),
    ]
