# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20160601_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerarticle',
            name='fulltext_or_mention',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('Full Text Publish', 'Full Text Publish'), ('Mention/Aggregation', 'Mention/Aggregation')], default='Full Text Publish', max_length=19, verbose_name='Publish Type'),
        ),
        migrations.AlterField(
            model_name='partnerarticle',
            name='properly_credited',
            field=models.NullBooleanField(default=True, verbose_name='Properly credited?'),
        ),
        migrations.AlterField(
            model_name='partnerarticle',
            name='radio_broadcast',
            field=models.NullBooleanField(default=False),
        ),
    ]
