# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0003_auto_20160607_2028'),
        ('business', '0007_auto_20160603_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_manager.MediaItem'),
        ),
    ]
