# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_partner_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=1, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status'),
        ),
    ]
