# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0003_auto_20160607_2028'),
        ('business', '0010_auto_20160610_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_with_image', to='media_manager.MediaItem'),
        ),
        migrations.AddField(
            model_name='partner',
            name='image_large',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_with_large_image', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='media_manager.MediaItem'),
        ),
    ]
