# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20160615_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_with_image', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image_large',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_with_large_image', to='media_manager.MediaItem'),
        ),
    ]
