# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20160616_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='featured_image_large',
        ),
    ]
