# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20160621_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('order',), 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='person',
            name='advisory_board',
            field=models.BooleanField(default=False, help_text='On Advisory Board'),
        ),
        migrations.AddField(
            model_name='person',
            name='director_board_member',
            field=models.BooleanField(default=False, help_text='On Board of Directors'),
        ),
        migrations.AddField(
            model_name='person',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='staff_member',
            field=models.BooleanField(default=False, help_text='Staff/Team member'),
        ),
    ]
