# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import fkchooser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20160622_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerarticle',
            name='article',
            field=fkchooser.fields.PopupForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Article'),
        ),
    ]
