# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20160629_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='person',
            name='exerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
