# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_auto_20160616_1144'),
        ('business', '0017_auto_20160629_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='MUST be decimal format not degrees, i.e. 34.05197222                      not 34°03\'07.1"N', max_digits=12, null=True, verbose_name='Latitude Decimal'),
        ),
        migrations.AddField(
            model_name='partner',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='MUST be decimal format not degrees, i.e. -118.2457222                      not 118°14\'44.6"W<br>\n                     NOTE: North American logitude ending in "W" should be                      a negative value!', max_digits=12, null=True, verbose_name='Longitude Decimal'),
        ),
        migrations.AddField(
            model_name='partner',
            name='map_partner_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('radio', 'Radio'), ('digital', 'Digital'), ('national', 'National')], default='standard', help_text='Digital and National partners                    DO NOT show on the map, but are listed on the sidebar', max_length=80, verbose_name='Map Partner Type'),
        ),
        migrations.AddField(
            model_name='partner',
            name='map_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_map_tooltip_thumbnail', to='media_manager.MediaItem'),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short description that shows in the map tooltip on hover', verbose_name='Map Description Text'),
        ),
        migrations.AddField(
            model_name='partner',
            name='show_on_map',
            field=models.BooleanField(default=False, help_text='Check to include on map and side list', verbose_name='Include in Map'),
        ),
    ]
