# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20160711_1607'),
        ('business', '0018_auto_20160708_0842'),
    ]

    operations = [
    ]
