# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, help_text='Will be auto-generated from the title.', max_length=2000, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.CharField(blank=True, help_text='Will be auto-generated from the title.', max_length=2000, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='partnerowner',
            name='slug',
            field=models.CharField(blank=True, help_text='Will be auto-generated from the title.', max_length=2000, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='person',
            name='exerpt',
            field=models.TextField(blank=True, null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.CharField(blank=True, help_text='Will be auto-generated from the title.', max_length=2000, null=True, verbose_name='Slug'),
        ),
    ]
