# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_auto_20160616_1144'),
        ('business', '0021_auto_20160713_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=1, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status')),
                ('publish_date', models.DateTimeField(blank=True, help_text="With Published chosen, won't be shown until this time", null=True, verbose_name='Published from')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('job_title', models.CharField(max_length=150, verbose_name='Job Title')),
                ('message', models.TextField(verbose_name='Testimonial Message')),
                ('order', models.CharField(default=0, max_length=3)),
                ('testimonial_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_image', to='media_manager.MediaItem', verbose_name='Testimonial Image')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'get_latest_by': 'created',
                'ordering': ['order', 'full_name'],
                'verbose_name': 'Testimonial',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Connects the `Person` object to a `User` that can log in If no `User` is selected, you can supply names and email below', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
