# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_auto_20160713_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Connects the `Person` object to a `User` that can log in If no `User` is selected, you can supply names and email below', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
