# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20160715_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'get_latest_by': 'created', 'ordering': ['display_order', 'full_name'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='order',
            new_name='display_order',
        ),
    ]
