# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_auto_20160715_1459'),
        ('business', '0022_auto_20160716_1055'),
    ]

    operations = [
    ]
