# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_auto_20160815_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_with_image', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image_large',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_with_large_image', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='map_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_map_tooltip_thumbnail', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='media_manager.MediaItem'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_image', to='media_manager.MediaItem', verbose_name='Testimonial Image'),
        ),
    ]
