# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 21:42
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(upload_to='uploads'),
        ),
    ]
