# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 20:28
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0002_auto_20160603_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'verbose_name': 'Media Item', 'verbose_name_plural': 'Media Items'},
        ),
        migrations.AlterModelOptions(
            name='mediasource',
            options={'verbose_name': 'Media Source', 'verbose_name_plural': 'Media Sources'},
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(upload_to='uploads/'),
        ),
    ]
