# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_auto_20160616_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Photographer / creator'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='image_type',
            field=models.CharField(blank=True, choices=[('photo', 'photo'), ('illustration', 'illustration'), ('graphic', 'graphic')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='license',
            field=models.CharField(blank=True, choices=[('calmatters owned', 'CALmatters owned'), ('licensed', 'Licensed'), ('creative commons', 'Creative Commons')], max_length=30, null=True),
        ),
    ]
